
require("./tests/isGraph/isGraph.js");
require("./tests/random/random.js");
require("./tests/getGraphVertices/getGraphVertices.js");
require("./tests/getGraphNeighbors/getGraphNeighbors.js");
require("./tests/isGraphConnected/isGraphConnected.js");
require("./tests/isGraphTree/isGraphTree.js");
require("./tests/generateGraphTree/generateGraphTree.js");
require("./tests/graphEdgeExists/graphEdgeExists.js");
require("./tests/tryAddGraphEdge/tryAddGraphEdge.js");
require("./tests/toGraphMinDegree3/toGraphMinDegree3.js");
require("./tests/getGraphDegree/getGraphDegree.js");
require("./tests/toGraphMaxDegree3SingleVertex/toGraphMaxDegree3SingleVertex.js");
require("./tests/toGraphMaxDegree3/toGraphMaxDegree3.js");
require("./tests/generateGraph/generateGraph.js");
// TODO: Fix the test
//require("./tests/toRegular3Graph/toRegular3Graph.js");

require("./tests/graphTraverse/graphTraverse.js");
require("./tests/to4Sat/1.js");
require("./tests/to4Sat/2.js");
require("./tests/is3Sat/1.js");
require("./tests/tryAdd4SatClause/1.js");
require("./tests/tryAdd4SatClause/2.js");
require("./tests/tryAdd4SatClause/3.js");
require("./tests/tryAdd4SatClause/4.js");
require("./tests/tryAdd4SatClause/5.js");
require("./tests/grow4Sat/1.js");
require("./tests/get4SatVariables/1.js");
require("./tests/toMax3Sat/1.js");
require("./tests/tryAddSatClause/1.js");
require("./tests/tryAddSatClause/2.js");
require("./tests/tryAddSatClause/3.js");
require("./tests/tryAddSatClause/4.js");
require("./tests/getSatVariables/1.js");
require("./tests/getLargestSatVariable/1.js");
require("./tests/getLargestSatVariable/2.js");
require("./tests/toMin3Sat/1.js");
require("./tests/parseSat/1.js");